[package]
authors = ["David Wallace Croft <david@CroftSoft.com>"]
categories = ["games"]
description = "Tank combat game using the A* algorithm"
edition = "2021"
homepage = "https://www.CroftSoft.com/"
keywords = ["algorithm"]
license = "MIT"
name = "com-crofsoft-app-mars"
publish = false
readme = "README.md"
repository = "https://github.com/david-wallace-croft/com-croftsoft-app-mars"
version = "0.0.0-SNAPSHOT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
